### ISSUE TITLE
Responses are shuffled/delayed on timeout

### ISSUE THREAD

**Issue by tannerblair** [rfporter/Modbus-Master#1]
This can be demonstrated most easily with TCP. I've used the NI Modbus API as the slave to show this in the snippet below. If you use a tool like [clumsy](https://jagt.github.io/clumsy/download) to drop packets, you will see that the master gets behind the slave, and occasionally the data read back corresponds to the other register.
![modbus issue](https://user-images.githubusercontent.com/12645089/40733029-5b00ed0a-63fa-11e8-979d-6233d77b2efc.png)

I think the long-term fix for this would be to:
- send each transaction with a unique transaction ID
- create a daemon that checks for responses from the slave and adds them to a hash table with the transaction ID as the key
- read the response for each method from the hash table instead of from the buffer

**Comment by rfporter** [comment]
Good catch.
Transaction ID was not implemented in this version of the TCP Modbus Master.

For simplicity, I tried to make the transaction an atomic operation, as with Modbus ASCII and RTU. That is, for a given Modbus session, you can only send one request at a time. The master waits for the response or times out before another request can be sent. 
For the ASCII and RTU modes this works because the read/write buffers are always flushed before a request is sent. This is not the case with the TCP mode.

As a temporary workaround, I suggest that if a timeout occurs in TCP mode, the TCP connection be reset. This will cancel any incomplete transactions.
![transaction id workaround](https://user-images.githubusercontent.com/6878763/40853971-d0e1fdb2-659d-11e8-9e2c-6aa5d0166efa.png)

**Comment by rfporter** [comment]
I will look into implementing your suggested fix in the next release.

**Comment by rfporter** [comment]
Proposed fix is located in the transaction ID fix branch.
More testing is required.

**Comment by rfporter** [comment]
fixed in v1.3.2
